version: '3.1'

services:
  payara:
    build: ../images/payara
    environment:
      - ADMIN_PASSWORD=adminadmin
    ports:
      - "8080:8080"
      - "4848:4848"
    #volumes:
    #  - ../code/target/gamification.war:/opt/payara/deployments/gamification.war
     
  db:
    build: ../images/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: amtdb
      MYSQL_ROOT_PASSWORD: root
        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
    restart: always
    ports:
     - 8888:80 

volumes:
  dbdata:
